const GET_DATA = 'GET_DATA'
const ADD_DATA = 'ADD_DATA'
const ADD_VACCINE = 'ADD_VACCINE'
const GET_NOT_VACCINED = 'GET_NOT_VACCINED'
const LOADING_DATA = 'LOADING_DATA'
const GET_INFO = 'GET_INFO'
const SEARCH_DATA = 'SEARCH_DATA'
const ERROR_DASHBOARD = 'ERROR_DASHBOARD'
const SICK_DATE = 'SICK_DATE'
const FILTER_DATA = 'FILTER_DATA'
const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
const OTHER_DATE = 'OTHER_DATE'
const DELETE_FIRST_COMPONENT = 'DELETE_FIRST_COMPONENT'
const DELETE_FINAL_COMPONENT = 'DELETE_FINAL_COMPONENT'
const DELETE_SICK_DATE = 'DELETE_SICK_DATE'
const DELETE_OTHER = 'DELETE_OTHER'
const ADD_ONE_COMPONENT = 'ADD_ONE_COMPONENT'

export {
    GET_DATA,
    ADD_DATA,
    ADD_VACCINE,
    GET_NOT_VACCINED,
    LOADING_DATA,
    GET_INFO,
    SEARCH_DATA,
    ERROR_DASHBOARD,
    SICK_DATE,
    FILTER_DATA,
    CLEAR_MESSAGE,
    OTHER_DATE,
    DELETE_OTHER,
    DELETE_SICK_DATE,
    DELETE_FINAL_COMPONENT,
    DELETE_FIRST_COMPONENT,
    ADD_ONE_COMPONENT
}