const GET_DATA = 'GET_DATA'
const ADD_DATA = 'ADD_DATA'
const ADD_VACCINE = 'ADD_VACCINE'
const GET_NOT_VACCINED = 'GET_NOT_VACCINED'
const LOADING_DATA = 'LOADING_DATA'
const GET_INFO = 'GET_INFO'


export {
    GET_DATA,
    ADD_DATA,
    ADD_VACCINE,
    GET_NOT_VACCINED,
    LOADING_DATA,
    GET_INFO
}