const GET_DATA = 'GET_DATA'
const ADD_DATA = 'ADD_DATA'
const ADD_VACCINE = 'ADD_VACCINE'
const GET_NOT_VACCINED = 'GET_NOT_VACCINED'
const LOADING_DATA = 'LOADING_DATA'
const GET_INFO = 'GET_INFO'
const SEARCH_DATA = 'SEARCH_DATA'
const ERROR_DASHBOARD = 'ERROR_DASHBOARD'
const SICK_DATE = 'SICK_DATE'
const FILTER_DATA = 'FILTER_DATA'
const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

export {
    GET_DATA,
    ADD_DATA,
    ADD_VACCINE,
    GET_NOT_VACCINED,
    LOADING_DATA,
    GET_INFO,
    SEARCH_DATA,
    ERROR_DASHBOARD,
    SICK_DATE,
    FILTER_DATA,
    CLEAR_MESSAGE
}